### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by LiXunGuan** [mxnjs/vue3-data-dict#1]
不好意思，提一个会被挨打的问题。就是我看不懂这个插件要怎么使用。我个人（厚着脸皮）建议，能否做一个在线的示例

**Comment by moxun1639** [comment]
可以参考
[简体中文](https://mxnjs.github.io/vue-data-dict-docs/zh/)API文档

示例代码
[mxnjs/vue-data-dict-examples](https://github.com/mxnjs/vue-data-dict-examples)
